// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://broewnzkfwaggbzsogvv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJyb2V3bnprZndhZ2dienNvZ3Z2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY1MDkzNTYsImV4cCI6MjA1MjA4NTM1Nn0.yPjIIgvQX5sp_D_8PsRRIVwhXQxabKdiqX5X4CduG3Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);